/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loader;

;
import Dao.jdbc.*;
import java.util.logging.Logger;
import javax.servlet.ServletContext;
import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;

/**
 * Web application lifecycle listener.
 *
 * @author Stefano Chirico &lt;stefano dot chirico at unitn dot it&gt;
 * @since 2017.05.24
 */
public class JdbcClassLoader implements ServletContextListener {

    /**
     * The serlvet container call this method when initializes the application
     * for the first time.
     *
     * @param sce the event fired by the servlet container when initializes the
     * application
     *
     * @author Stefano Chirico
     * @since 1.0.170524
     */
    @Override
    public void contextInitialized(ServletContextEvent sce) {
        ServletContext sc = sce.getServletContext();

        try {
            sc.setAttribute("userDao", new JdbcUserDao());
            sc.setAttribute("anomaliesDao", new JdbcAnomalieDao());
            sc.setAttribute("cartDao", new JdbcCartDao());
            sc.setAttribute("pictureDao", new JdbcPictureDao());
            sc.setAttribute("productDao", new JdbcProductDao());
            sc.setAttribute("purchaseDao", new JdbcPurchaseDao());
            sc.setAttribute("reviewDao", new JdbcReviewDao());
            sc.setAttribute("shopDao", new JdbcShopDao());
            //only for debugger
            
        } catch (Exception ex) {

        }
    }

    /**
     * The servlet container call this method when destroyes the application.
     *
     * @param sce the event generated by the servlet container when destroyes
     * the application.
     *
     * @author Stefano Chirico
     * @since 1.0.170524
     */
    @Override
    public void contextDestroyed(ServletContextEvent sce) {
    }
}